AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda directly from folder

parameters:
  NASA_api_KEY:
    Type: String
    Description: API key for NASA API
  
  Mandi_API_KEY:
    Type: String
    Description: API key for Mandi API

  AWS_Pandas_layer:
    Type: String
    Description: ARN for the AWS SDK for Pandas layer

  OIDC_Role:
    Type: String
    Description: OIDC role for the Lambda function

Resources:

  TestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-lambda
    Description: API key for Mandi API

  

Resources:

  TestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-lambda
      Runtime: python3.12
      Handler: app.handler
      CodeUri: ../lambda/test_lambda/


  NasaIngestionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nasa-ingestion-lambda
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: ../lambda/nasa_data_ingestion/
      Timeout: 900
      Environment:
        Variables:
          BUCKET_NAME: ut-raw-bucket
          NASA_API_KEY: !Ref NASA_api_KEY
      Layers:
        - !Ref AWS_Pandas_layer
      Role: !Sub arn:aws:iam::515966539109:role/${OIDC_Role}
