AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda directly from folder

Resources:

  TestLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-lambda
      Runtime: python3.12
      Handler: app.handler
      CodeUri: ../lambda/test_lambda/


  NasaIngestionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nasa-ingestion-lambda
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: ../lambda/nasa_data_ingestion/
      Environment:
        Variables:
          BUCKET_NAME: ut-raw-bucket
          NASA_API_KEY: DccQPkmpWNG6Ni07npPxEf2tkDI5Sko62vjfarmz
      Layers:
        - arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python312:24
      Role: arn:aws:iam::515966539109:role/UT_LambdaServiceRole
