AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy S3 bucket

Resources:

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ut-raw-bucket
      AccessControl: Private