AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy IAM role

Resources:

  Lambdaservicerole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: UT_LambdaServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: UT_LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - lambda:*
                Resource: "*"