name: Deploy to AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        role-to-assume: arn:aws:iam::515966539109:role/OIDC_UT_DeployRole
        aws-region: us-east-2

    - name: Build Lambda
      run: sam build --template-file templates/resource.yml

    - name: Deploy Lambda
      run: sam deploy --stack-name test-lambda-stack --capabilities CAPABILITY_IAM
